# Generated by Django 2.1 on 2019-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_type', models.CharField(max_length=200)),
                ('prod_price', models.FloatField(default=0)),
                ('prod_image', models.ImageField(upload_to='')),
                ('prod_time', models.DateTimeField(auto_now_add=True, verbose_name='upload_time')),
            ],
        ),
    ]
